<script type="text/javascript">
//<![CDATA[
	
	var auctionTimeCounters = new Array();
	var i = 0;
//]]>
</script>	
<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<div class="note-msg">
    <?php /*echo $this->__('There are no auction products.')*/ echo $this->__('Er zijn op dit moment geen lopende veilingen. Kom later nog eens terug!') ?>
</div>
<?php else: ?>
<?php $now_time = Mage::getModel('core/date')->timestamp(time()) ?>
<?php $modelAuction = Mage::getModel('auction/productauction') ?>
<?php echo $this->getToolbarHtml() ?>
<div class="listing-type-grid catalog-listing" id="gridauction3">
<?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if($i++%$_columnCount==0): ?>
        <ol class="products-grid first odd">
        <?php endif; ?>
	<?php $auction	= $modelAuction->loadAuctionByProductId($_product->getId()) ?>
	<?php $lastBid = $auction->getLastBid() ?>
	<?php $totalBid = $auction->getTotalBid() ?>
	<?php $currentPrice = $lastBid->getPrice() ? $lastBid->getPrice() : $auction->getInitPrice() ?>	
	<?php $end_time = strtotime($auction->getEndTime() .' '. $auction->getEndDate()) ?>	
	<?php $url_history = $this->getHistoryUrl($auction); ?>
    			<li class="item">
                <h5><?php 
				$time_now = time();
				$time_difference = $end_time - $time_now;
				if ($time_difference < 90000) {
					echo '<img src="https://jatica.be/skin/frontend/default/f001/images/animatedfire.gif" alt="HOT" height="22" width="22" class="vlammeke"/>';
					}
				 ?><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
					<?php echo $this->htmlEscape($_product->getName()) ?></a>
				</h5>
                <?php /*echo $this->getPriceHtml($_product, true) */ ?>
                <p class="product-image">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135, 135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
                    </a>
                </p>
                <?php 
			/*echo "endtime: ".$end_time;
			echo "; time now: ".$time_now;
			echo "; difference: ".$time_difference;*/		
			 ?>
             <?php 
			 if ($time_difference < 0) 
			 { 
			 echo '<div class="auction_ended">Deze veiling is afgelopen</div>'; 
			 } else { ?>
			<div <?php if ($time_difference < 90000) { echo ' STYLE="color: red"'; } ?> class="timeleft" id="timeleft_<?php echo $_product->getId() ?>"> </div>	<?php } ?>
			<div id="auction_info_<?php echo $_product->getId()?>">				
				<div class="row"> <center>
					<span class="current_price" id="current_price<?php echo $_product->getId()?>">
						<?php echo Mage::helper('core')->currency($currentPrice) ?>
					</span> </center>
					<div class="clear"></div>
				</div>
				<div class="row"> <center>
					<span class="bidder" id="bidder<?php echo $_product->getId()?>">Hoogste bieder: 
						<?php echo $lastBid ? $lastBid->getBidderName() : $this->__('None') ?>
					</span> </center>
					<div class="clear"></div>
				</div>	
				<input type="hidden" id="codecolor<?php echo $_product->getId()?>" name="codecolor" value="0"  >		
				<input type="hidden" id="current_bid_id_<?php echo $_product->getId() ?>" value="<?php echo $lastBid->getId() ?>" />
			</div>
			<div id="results_update_auction_<?php echo $_product->getId() ?>" style="display:none;">
			</div>
		</li>
<script type="text/javascript">
//<![CDATA[
	auctionTimeCounters[i] = new AuctionTimeCounter('<?php echo $now_time ?>', '<?php echo $end_time ?>', '<?php echo $auction->getId() ?>', '<?php echo $this->__(' day, ') ?>', '<?php echo $this->__(' days, ') ?>', '<?php echo $this->__(' month, ') ?>', '<?php echo $this->__(' months, ') ?>', '<?php echo $this->__(' year, ') ?>', '<?php echo $this->__(' years, ') ?>');
	auctionTimeCounters[i].setTimeleft('timeleft_<?php echo $_product->getId() ?>');
	updateAuctionListInfo('auction_info_<?php echo $_product->getId() ?>','<?php echo Mage::getBaseUrl('js') ?>magestore/auction.php?<?php echo http_build_query(array('tmpl' => 'auctionlistinfo')) ?>','<?php echo $_product->getId() ?>','<?php echo $auction->getId() ?>');
	i++;
	setBackground('current_price','<?php echo $_product->getId() ?>');	
	setBackground('bidder','<?php echo $_product->getId() ?>');
//]]>
</script>			
        <?php if($i%$_columnCount==0 || $i==$_collectionSize): ?>
	</ol>
	<div class="clear"></div>
        <?php endif; ?>
	<div id="init_price<?php echo $_product->getId()?>" style="display: none;">
		<?php echo Mage::helper('core')->currency($auction->getInitPrice()) ?>
	</div>
    <?php endforeach ?>
    <script type="text/javascript">
		decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);
		<?php
		$baseCurrency = Mage::app()->getStore()->getBaseCurrency();
		$currCurrency = Mage::app()->getStore()->getCurrentCurrency();
		?>
		var currencyConvert = new CurrencyConvert('<?php echo $baseCurrency->format(1000,array(),false) ?>','<?php echo $currCurrency->format(1000,array(),false) ?>',<?php echo Mage::app()->getStore()->convertPrice(1) ?>);
		
	</script>
</div>
<?php echo $this->getToolbarHtml() ?>
<?php endif; ?>
<style type="text/css">	
	<?php echo Mage::getStoreConfig('auction/design/css') ?>
</style>
